name = "balanced"
description = "Discord ve Roblox için dengeli TLS/QUIC ve RTC desync"
hostlist = "/usr/share/turkdpi/services-hosts.txt"
tcp_args = ["--filter-tcp=80,443", "--filter-l7=http,tls", "--dpi-desync=fake,multisplit", "--dpi-desync-split-pos=1,midsld", "--dpi-desync-fooling=badsum", "--dpi-desync-repeats=4", "--dpi-desync-cutoff=n8"]
udp_args = ["--filter-udp=*", "--filter-l7=discord,stun", "--dpi-desync=fake", "--dpi-desync-fooling=badsum", "--dpi-desync-repeats=4", "--dpi-desync-cutoff=n6", "--new", "--filter-udp=443", "--filter-l7=quic", "--hostlist=/usr/share/turkdpi/services-hosts.txt", "--dpi-desync=fake", "--dpi-desync-fooling=badsum", "--dpi-desync-repeats=4", "--dpi-desync-cutoff=n6"]
