name = "safe"
description = "Discord ve Roblox için düşük müdahaleli TLS/QUIC ve Discord RTC"
hostlist = "/usr/share/turkdpi/services-hosts.txt"
tcp_args = ["--filter-tcp=80,443", "--filter-l7=http,tls", "--dpi-desync=multisplit", "--dpi-desync-split-pos=1,midsld"]
udp_args = ["--filter-udp=*", "--filter-l7=discord,stun", "--dpi-desync=fake", "--dpi-desync-fooling=badsum", "--dpi-desync-repeats=2", "--dpi-desync-cutoff=n4", "--new", "--filter-udp=443", "--filter-l7=quic", "--hostlist=/usr/share/turkdpi/services-hosts.txt", "--dpi-desync=fake", "--dpi-desync-fooling=badsum", "--dpi-desync-repeats=2", "--dpi-desync-cutoff=n4"]
